version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
      timezone: "UTC"
    target-branch: "dev"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "release:patch"
    commit-message:
      prefix: "chore(deps)"
    ignore:
      - dependency-name: "nuxt"
        update-types: ["version-update:semver-major"]
